package jiafen.jinniu.com;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ADD_HISTORY".
 */
@Entity
public class Add_history {

    @Id
    private Long id;
    private int count;

    @NotNull
    private String place;
    private long time;

    @Generated
    public Add_history() {
    }

    public Add_history(Long id) {
        this.id = id;
    }

    @Generated
    public Add_history(Long id, int count, String place, long time) {
        this.id = id;
        this.count = count;
        this.place = place;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    @NotNull
    public String getPlace() {
        return place;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlace(@NotNull String place) {
        this.place = place;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

}
