package jiafen.jinniu.com;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jiafen.jinniu.com.Girl;
import jiafen.jinniu.com.Add_history;
import jiafen.jinniu.com.PhoneNumber;

import jiafen.jinniu.com.GirlDao;
import jiafen.jinniu.com.Add_historyDao;
import jiafen.jinniu.com.PhoneNumberDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig girlDaoConfig;
    private final DaoConfig add_historyDaoConfig;
    private final DaoConfig phoneNumberDaoConfig;

    private final GirlDao girlDao;
    private final Add_historyDao add_historyDao;
    private final PhoneNumberDao phoneNumberDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        girlDaoConfig = daoConfigMap.get(GirlDao.class).clone();
        girlDaoConfig.initIdentityScope(type);

        add_historyDaoConfig = daoConfigMap.get(Add_historyDao.class).clone();
        add_historyDaoConfig.initIdentityScope(type);

        phoneNumberDaoConfig = daoConfigMap.get(PhoneNumberDao.class).clone();
        phoneNumberDaoConfig.initIdentityScope(type);

        girlDao = new GirlDao(girlDaoConfig, this);
        add_historyDao = new Add_historyDao(add_historyDaoConfig, this);
        phoneNumberDao = new PhoneNumberDao(phoneNumberDaoConfig, this);

        registerDao(Girl.class, girlDao);
        registerDao(Add_history.class, add_historyDao);
        registerDao(PhoneNumber.class, phoneNumberDao);
    }
    
    public void clear() {
        girlDaoConfig.getIdentityScope().clear();
        add_historyDaoConfig.getIdentityScope().clear();
        phoneNumberDaoConfig.getIdentityScope().clear();
    }

    public GirlDao getGirlDao() {
        return girlDao;
    }

    public Add_historyDao getAdd_historyDao() {
        return add_historyDao;
    }

    public PhoneNumberDao getPhoneNumberDao() {
        return phoneNumberDao;
    }

}
