package jiafen.jinniu.com;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PHONE_NUMBER".
*/
public class PhoneNumberDao extends AbstractDao<PhoneNumber, Long> {

    public static final String TABLENAME = "PHONE_NUMBER";

    /**
     * Properties of entity PhoneNumber.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property His_id = new Property(1, long.class, "his_id", false, "HIS_ID");
        public final static Property Phonenum = new Property(2, int.class, "phonenum", false, "PHONENUM");
    };


    public PhoneNumberDao(DaoConfig config) {
        super(config);
    }
    
    public PhoneNumberDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PHONE_NUMBER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"HIS_ID\" INTEGER NOT NULL ," + // 1: his_id
                "\"PHONENUM\" INTEGER NOT NULL );"); // 2: phonenum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PHONE_NUMBER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PhoneNumber entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getHis_id());
        stmt.bindLong(3, entity.getPhonenum());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PhoneNumber entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getHis_id());
        stmt.bindLong(3, entity.getPhonenum());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PhoneNumber readEntity(Cursor cursor, int offset) {
        PhoneNumber entity = new PhoneNumber( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // his_id
            cursor.getInt(offset + 2) // phonenum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PhoneNumber entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHis_id(cursor.getLong(offset + 1));
        entity.setPhonenum(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PhoneNumber entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PhoneNumber entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
